### ISSUE TITLE
:open_umbrella: setup guidelines for contributing

### ISSUE THREAD

**Issue by scarf005** [scarf005/Marisa#102]
### Summary

- [ ] add `CONTRIBUTING.md`
	- [ ] move install guides to `CONTRIBUTING.md`
	- [ ] add commit style guide
- [ ] add `LOCALIZATION.md`
- [ ] setup code style
- [x] fix obsolete gradle task description
- [x] #103
- [x] #109
- [x] label new PRs
- [ ] add description about steamworks error code
- [x] #155
- [ ] guide on how to enable basemod terminal
