### ISSUE TITLE
:open_umbrella: deprecate `gold`, `relic`, and `potion` themed cards

### ISSUE THREAD

**Issue by scarf005** [scarf005/Marisa#125]
### Summary

based on conversation in #120 (feel free to ask me to translate the discussions), following cards are to be deprecated due to not playing well with other archtypes (burn, charge, amplify, etc):

#### gold based
- `Witch Of Greed`
- `Robbery`

#### relic based
- `TreasureHunter`
- `Collecting Quirk`
- `Portable Prop Bag`

### Tasks
- [ ] refactor config management
	- [ ] learn to manage config file in kotlin
	- [ ] use localization for config
- [ ] add an config to hide cards from cards pool
	- [ ] gold based cards
	- [ ] relic based cards
