### ISSUE TITLE
publish to steam workshop

### ISSUE THREAD

**Issue by scarf005** [scarf005/Marisa#46]
- [x] remove stale files
- [x] update `modthespire.json`
- [x] setup semantic release
- [x] use timestamp for dev
- [x] use semantic version for release
