### ISSUE TITLE
☂️ deployment automation

### ISSUE THREAD

**Issue by scarf005** [scarf005/Marisa#90]
- [ ] add https://github.com/scarf005/changelog as gradle dependency
- [x] automated release via [github cli](https://cli.github.com/manual/gh_release_create)
- [x] automated publishing to steam
- [x] automated pr generation

**Comment by scarf005** [comment]
closing since basic automation pipeline is finished.
a new umbrella issue will be raised for advanced deployment automation.
```sh
# generate changelog using scarf005/changelog
gradle run
# create PR
./pr.py
# publish to github and steam workshop
./releases.py github
```
